# Generated by Django 4.1.3 on 2022-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estreno', models.CharField(max_length=500)),
                ('fecha_estreno', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Consola',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(max_length=500),
        ),
    ]
