# Generated by Django 4.1.3 on 2022-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_estreno_delete_consola_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estreno',
            name='fecha_estreno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.CharField(max_length=50),
        ),
    ]
